export enum OrderExceptionCode {
  INSUFFICIENT_STOCK = 'OR-001',
  INACTIVE_PRODUCT = 'OR-002',
  EMPTY_CART = 'OR-003',
  DELIVERED_ORDER = 'OR-004',
  CANCELLED_ORDER = 'OR-005',
  NOT_PENDING_ORDER = 'OR-006',
  NOT_FOUND = 'OR-NF',
}
